# Generated by Django 5.0.4 on 2024-04-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock_symbol', models.ImageField(upload_to='uploads/stocks', verbose_name='stock_symbol')),
                ('change', models.CharField(max_length=50, verbose_name='change')),
                ('market_cap', models.CharField(max_length=50, verbose_name='Market Cap')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'StockList',
                'verbose_name_plural': 'StockLists',
            },
        ),
    ]
