# Generated by Django 5.0.4 on 2024-04-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='stock_symbol',
            field=models.FileField(upload_to='uploads/stocks', verbose_name='Image'),
        ),
    ]
