# Generated by Django 5.0.4 on 2024-04-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0002_alter_stocklist_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Short Name'),
        ),
    ]
