# Generated by Django 5.0.4 on 2024-04-18 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0005_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(max_length=50, verbose_name='Trade Type')),
                ('trade_price', models.IntegerField(verbose_name='Trade Price')),
                ('trade_amount', models.IntegerField(verbose_name='Trade Amount')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketApp.stocklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TradeHistory',
                'verbose_name_plural': 'TradeHistories',
            },
        ),
    ]
